apiVersion: 1

datasources:
  - name: Prometheus-vm
    type: prometheus
    uid: prometheus-vm-uid
    url: ${PROVISIONING_VICTORIAMETRICS_URL}
    access: proxy
    isDefault: false
    editable: true
