volumes:
  certs:
  elastic1:
  kibanadata:
  logstashdata:


services:
  autoheal:
    image: "willfarrell/autoheal:${PROJECT_AUTOHEAL_IMAGE_VERSION:-latest}"
    container_name: autoheal
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AUTOHEAL_CONTAINER_LABEL: ${PROJECT_COMPOSE_NAME}.autoheal
      AUTOHEAL_INTERVAL: 10


  setup:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${PROJECT_ELK_IMAGE_VERSION:-9.2.1}"
    restart: no
    user: "0"
    command: >
      bash -c '
        if [ x${PROJECT_ELASTIC_PASSWORD} == x ]; then
          echo "Set the PROJECT_ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${PROJECT_ELASTIC_KIBANA_PASSWORD} == x ]; then
          echo "Set the PROJECT_ELASTIC_KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: elastic1\n"\
          "    dns:\n"\
          "      - elastic1\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions";
        chown -R root:root config/certs;
        find . -type d -exec chmod 755 \{\} \;;
        find . -type f -exec chmod 644 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://elastic1:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${PROJECT_ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://elastic1:9200/_security/user/kibana_system/_password -d "{\"password\":\"${PROJECT_ELASTIC_KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "Creating logstash_writer role";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${PROJECT_ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://elastic1:9200/_security/role/logstash_writer -d \
        "{ \
          \"cluster\": [\"manage_index_templates\", \"monitor\", \"manage_ilm\"], \
          \"indices\": [ \
            { \
              \"names\": [\"logstash-*\"], \
              \"privileges\": [\"write\", \"create\", \"create_index\", \"manage\", \"manage_ilm\"] \
            } \
          ] \
        }" | grep -q "\"created\":true"; do sleep 10; done;
        echo "Creating logstash_internal user";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${PROJECT_ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://elastic1:9200/_security/user/logstash_internal -d \
        "{ \
          \"password\" : \"${PROJECT_ELASTIC_LOGSTASH_PASSWORD}\", \
          \"roles\" : [ \"logstash_writer\" ], \
          \"full_name\" : \"Internal Logstash User\" \
        }" | grep -q "\"created\":true"; do sleep 10; done;
        echo "All done!";
      '
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/elastic1/elastic1.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120


  elastic1:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${PROJECT_ELK_IMAGE_VERSION:-9.2.1}"
    restart: unless-stopped
    depends_on:
      setup:
        condition: service_healthy
    ports:
      - 9200:9200
    environment:
      - ELASTIC_PASSWORD=${PROJECT_ELASTIC_PASSWORD}
      - cluster.name=mycluster
      - node.name=node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/elastic1/elastic1.key
      - xpack.security.http.ssl.certificate=certs/elastic1/elastic1.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/elastic1/elastic1.key
      - xpack.security.transport.ssl.certificate=certs/elastic1/elastic1.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
      - xpack.ml.use_auto_machine_memory_percent=true
      - cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - elastic1:/usr/share/elasticsearch/data
    mem_limit: 5GB
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'"]
      interval: 10s
      timeout: 10s
      retries: 120
    labels:
      - ${PROJECT_COMPOSE_NAME}.autoheal="true"


  kibana:
    image: "docker.elastic.co/kibana/kibana:${PROJECT_ELK_IMAGE_VERSION:-9.2.1}"
    restart: unless-stopped
    depends_on:
      elastic1:
        condition: service_healthy
    ports:
      - 5601:5601
    environment:
      - SERVER_NAME=${PROJECT_KIBANA_DOMAIN}
      - SERVER_BASEPATH=/kibana
      - ELASTICSEARCH_HOSTS=["https://elastic1:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${PROJECT_ELASTIC_KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=["/usr/share/kibana/config/certs/ca/ca.crt"]
      - XPACK_SECURITY_ENCRYPTIONKEY=${PROJECT_KIBANA_SESSION_KEY}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${PROJECT_KIBANA_STORAGE_KEY}
    volumes:
      - certs:/usr/share/kibana/config/certs:ro
      - kibanadata:/usr/share/kibana/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'"]
      interval: 30s
      timeout: 10s
      retries: 120
    labels:
      - ${PROJECT_COMPOSE_NAME}.autoheal="true"


  logstash:
    image: "docker.elastic.co/logstash/logstash:${PROJECT_ELK_IMAGE_VERSION:-9.2.1}"
    restart: unless-stopped
    depends_on:
      elastic1:
        condition: service_healthy
    ports:
      - 5044:5044
    volumes:
      - certs:/usr/share/logstash/config/certs:ro
      - ./logstash:/usr/share/logstash/pipeline
      - logstashdata:/usr/share/logstash/data
    environment:
      - NODE_NAME=logstash
      - PROJECT_ELASTIC_LOGSTASH_PASSWORD=${PROJECT_ELASTIC_LOGSTASH_PASSWORD}
    mem_limit: 1GB
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9600/_node/hot_threads"]
      interval: 10s
      timeout: 10s
      retries: 3


  nginx:
    image: "nginx:${PROJECT_NGINX_IMAGE_VERSION:-alpine}"
    restart: unless-stopped
    depends_on:
      kibana:
        condition: service_healthy
    ports:
      - 80:8080
    volumes:
      - ./nginx_configs:/etc/nginx/conf.d
    healthcheck:
      test: ["CMD", "curl", "--fail", "--fail-early", "localhost:8080"]
    labels:
      - ${PROJECT_COMPOSE_NAME}.autoheal="true"
